Modal component
js-tasks-ru/htmlcss-20231027_tinaatimkovaa pull request #13
Opened 2023-11-23 08:52 UTC by tinatimkova

2023-11-23 19:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-23 21:05 UTC, GSemikozov requested changes

2023-11-23 21:05 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
fixed

2023-11-23 21:05 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
а здесь уже absolute

2023-11-24 20:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-27 03:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-28 20:56 UTC, GSemikozov approved these changes

2023-11-28 20:56 UTC, merged