Button component
js-tasks-ru/htmlcss-20231027_tinaatimkovaa pull request #6
Opened 2023-11-06 16:18 UTC by tinatimkova

2023-11-06 16:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 02:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-08 09:21 UTC, GSemikozov requested changes

2023-11-08 09:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import '../../assets/css/main.css';
глобальные стили ни в коем случае никогда не импортируем в файлы стилей компонентов) наоборот - компоненты подключаем в main

2023-11-08 09:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину не стоит жестко фиксировать

2023-11-08 09:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
не хватает паддингов и стилей для текста

2023-11-08 09:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn__primary {
модификаторы пишем через `_`

2023-11-08 09:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn__primary {
и в модификаторах описывает только то специфическое, что изменяем по отношению к тому, к чему этот модификатор применяем) то есть в нашем случае здесь должны быть свойства цвета текста, фона и возможно бордера, все остальное - общее для всех типов кнопок

2023-11-08 09:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
лучше pointer-events: none

2023-11-08 09:21 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <button class="btn btn__alt btn__alternate_disabled" disabled>Alternate</button>
вместо класса для disabled лучше использовать общий .button:disabled в css и в разметке - атрибут disabled

2023-11-11 20:17 UTC, GSemikozov requested changes

2023-11-11 20:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 66px;
при таких паддингах высота кнопки не будет 48 как в макете) лучше тогда зафиксировать высоту

2023-11-13 20:04 UTC, tinatimkova commented on 03-lection1/01-button/button.css
> +    padding: 15px 66px;
убрала паддинги

2023-11-15 21:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 66px;
неа, лучше было сделать `15 66 14` + `height: 48`

2023-11-15 21:10 UTC, GSemikozov requested changes

2023-11-15 21:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину фиксировать не надо, удалим

2023-11-19 22:21 UTC, tinatimkova commented on 03-lection1/01-button/button.css
> +    padding: 15px 66px;
тогда у меня кнопки разной ширины будут. мне нужно будет паддинги для каждого типа прописывать?

2023-11-22 06:28 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 66px;
неа, они и должны быть разной ширины = зависеть от вложенного контента)

2023-11-22 06:28 UTC, GSemikozov approved these changes

2023-11-22 06:28 UTC, merged