Basic accordion component
js-tasks-ru/htmlcss-20231027_tinaatimkovaa pull request #7
Opened 2023-11-08 02:21 UTC by tinatimkova

2023-11-08 02:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 09:22 UTC, GSemikozov requested changes

2023-11-08 09:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import '../../assets/css/main.css';
см коммент по кнопкам

2023-11-08 09:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ширину и высоту не нужно фиксировать

2023-11-08 09:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 8px;
`24 32`

2023-11-08 09:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 8px;
нужен только марджин снизу

2023-11-08 09:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border-radius: 5px;
8

2023-11-08 09:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 32px;
а здесь тогда не надо

2023-11-08 09:22 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    display: inline-block;
лишнее

2023-11-08 18:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-09 07:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-09 20:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-10 06:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-10 06:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-11 20:19 UTC, GSemikozov requested changes

2023-11-11 20:19 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.wrapper {
вот такие врапперы - это вспомогательные стили, это не часть блока, поэтому их здесь описывать не надо, нет необходимости

2023-11-11 20:19 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border-radius: 5px;
не исправлено)

2023-11-13 20:12 UTC, tinatimkova commented on 03-lection1/02-accordion/accordion.css
> +.wrapper {
можно тогда фиксировать высоту и ширину на уровне блока? или выносить эти стили в main.css?

2023-11-15 21:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.wrapper {
неа, просто в отдельный файл стилей для страницы в которой делаем пример верстки, или можно вообще в тег style положить (на той же странице с примером). Смысл в том, чтобы держать файлы компонентов "чистыми", то есть они должны содержать в себе только стили для конкретного компонента

2023-11-15 21:13 UTC, GSemikozov approved these changes

2023-11-15 21:13 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-11-22 06:30 UTC, GSemikozov requested changes
все в порядке, но - конфликт, надо исправить

2023-11-23 21:02 UTC, GSemikozov approved these changes

2023-11-23 21:02 UTC, merged